### ISSUE TITLE
Using numbers >64bits

### ISSUE THREAD

**Issue by ranchalp** [nxt4hll/roccc-2.0#4]
Hi,

I would like to know if your compiler supports in operations over numbers bigger than 64bits.
Most of your examples use the int type, which is not big enough for what I would like to use it. I would like to know how could I achieve this (provided that I cannot use any C-library such as GMP or NTL).
The bigger bitsize I can use for addition and multiplication the better.

Thanks in advance,

Alejandro.

**Comment by nxt4hll** [comment]
The User and Developer Manuals explains how to define new bit sizes types. It follows the C types and can be set accordingly by setting the SIZE_MAX.
